/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_xpdftools_pdftotextc_HelloWorldJNI */

#ifndef _Included_io_xpdftools_pdftotextc_HelloWorldJNI
#define _Included_io_xpdftools_pdftotextc_HelloWorldJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_xpdftools_pdftotextc_HelloWorldJNI
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT jstring JNICALL Java_io_xpdftools_pdftotextc_HelloWorldJNI_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif