/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_hello1_HelloWorldJNI */

#ifndef _Included_jni_hello1_HelloWorldJNI
#define _Included_jni_hello1_HelloWorldJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_hello1_HelloWorldJNI
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jni_hello1_HelloWorldJNI_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
