name: CI
on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
      fail-fast: false
    steps:
      - name: Setup JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'liberica'
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: ./mvnw --batch-mode clean compile
      - name: Test
        run: ./mvnw --batch-mode verify
  install:
    name: Install
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Install GPG Secret Key
        run: cat <(echo -e "${{ secrets.GPG_SECRET_KEY }}") | gpg --batch --import
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install to Local Repository
        env:
          CENTRAL_USERNAME_TOKEN: ${{ secrets.CENTRAL_USERNAME_TOKEN }}
          CENTRAL_PASSWORD_TOKEN: ${{ secrets.CENTRAL_PASSWORD_TOKEN }}
        run: |
          maven_args="--batch-mode"
          maven_opts="-Dmaven.source.skip=false -Dmaven.javadoc.skip=false -Dgpg.skip=false -Dgpg.passphrase=${{ secrets.GPG_SECRET_KEY_PASSPHRASE }} -DskipTests"
          ./mvnw $maven_args clean install $maven_opts